import { type ColorScale } from '@/components/ColorMapChooser';
import {
  interpolateSpectral,
  interpolateViridis,
  interpolatePlasma,
  interpolateInferno,
  interpolateMagma,
  interpolateRdYlBu,
  interpolateRdYlGn,
  interpolateBrBG,
  interpolatePiYG,
  interpolatePuOr,
  interpolateBlues,
  interpolateGreens,
  interpolateReds,
  interpolateOranges,
  interpolatePurples,
  interpolatePuRd,
} from 'd3-scale-chromatic';

export const colorScales: Record<ColorScale, (t: number) => string> = {
  aqi: (t: number) => interpolateBlues(t),
  blues: interpolateBlues,
  greens: interpolateGreens,
  reds: interpolateReds,
  oranges: interpolateOranges,
  purples: interpolatePurples,
  pinks: interpolatePuRd,
  viridis: interpolateViridis,
  plasma: interpolatePlasma,
  inferno: interpolateInferno,
  magma: interpolateMagma,
  rdylbu: interpolateRdYlBu,
  rdylgn: interpolateRdYlGn,
  spectral: (t: number) => interpolateSpectral(1 - t),
  brbg: interpolateBrBG,
  piyg: interpolatePiYG,
  puor: interpolatePuOr,
};
