/**
 * NFHS-5 showcase demo datasets for the "Load Demo" button.
 * Each click cycles through indicators in shuffled order without repeats.
 *
 * Data source: NFHS-5 (2019-21), Government of India
 * Generated by scripts/generate_nfhs_demo_csvs.py
 */

import showcaseData from './showcase-demo-urls.json';

const entries = showcaseData as Record<string, { url: string; title: string }>;

export interface ShowcaseDemo {
  id: string;
  title: string;
  url: string;
}

export interface ShowcaseDemoResult {
  demo: ShowcaseDemo;
  index: number;   // 1-based position in the shuffled order
  total: number;
}

function buildDemos(prefix: 'states' | 'districts'): ShowcaseDemo[] {
  return Object.entries(entries)
    .filter(([key]) => key.startsWith(prefix + '_'))
    .map(([key, { url, title }]) => ({ id: key, title, url }));
}

export const STATE_DEMOS: ShowcaseDemo[] = buildDemos('states');
export const DISTRICT_DEMOS: ShowcaseDemo[] = buildDemos('districts');

// Shuffled queues so users see all indicators before repeats
function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

const queues: Record<string, { items: ShowcaseDemo[]; pos: number }> = {};

// Districts open on population density, then cycle the shuffled NFHS-5 indicators.
const DEFAULT_FIRST: Record<string, string> = { districts: 'districts_00_population_density' };

// Put the default demo first, shuffle the rest. Falls back to a plain shuffle
// if the default id isn't present.
function seededQueue(mode: string, demos: ShowcaseDemo[]): ShowcaseDemo[] {
  const firstId = DEFAULT_FIRST[mode];
  const first = firstId && demos.find(d => d.id === firstId);
  if (!first) return shuffle(demos);
  return [first, ...shuffle(demos.filter(d => d.id !== firstId))];
}

export function getNextDemo(mode: 'states' | 'districts'): ShowcaseDemoResult {
  const demos = mode === 'states' ? STATE_DEMOS : DISTRICT_DEMOS;

  if (!queues[mode] || queues[mode].pos >= queues[mode].items.length) {
    queues[mode] = { items: seededQueue(mode, demos), pos: 0 };
  }

  const q = queues[mode];
  const demo = q.items[q.pos];
  q.pos++;

  return { demo, index: q.pos, total: demos.length };
}

// Keep backward compat
export function getRandomDemo(mode: 'states' | 'districts'): ShowcaseDemo {
  return getNextDemo(mode).demo;
}
