// Generated by scripts/11_build_nwdp_village_layers.py - do not edit by hand.
// One entry per state with Survey of India village boundaries (NWDP, NWIC).
export interface NwdpVillageStateLayer {
  slug: string;
  stateName: string;
  displayName: string;
  features: number;
  templateUrl: string;
  googleSheetUrl?: string;
}

export const NWDP_VILLAGE_GEOJSON_BASE = 'https://geo.bharatviz.org/geojsons/admin/villages-nwdp';
export const NWDP_VILLAGE_POINTS_URL = 'https://geo.bharatviz.org/geoparquet/points/nwdp_village_points.parquet';

export const NWDP_VILLAGE_STATE_LAYERS: NwdpVillageStateLayer[] = [
  {"slug": "andaman-and-nicobar-islands", "stateName": "ANDAMAN & NICOBAR", "displayName": "Andaman & Nicobar Islands", "features": 669, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/andaman-and-nicobar-islands_template.csv"},
  {"slug": "andhra-pradesh", "stateName": "ANDHRA PRADESH", "displayName": "Andhra Pradesh", "features": 18100, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/andhra-pradesh_template.csv"},
  {"slug": "arunachal-pradesh", "stateName": "ARUNACHAL PRADESH", "displayName": "Arunachal Pradesh", "features": 5803, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/arunachal-pradesh_template.csv"},
  {"slug": "assam", "stateName": "ASSAM", "displayName": "Assam", "features": 26662, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/assam_template.csv"},
  {"slug": "bihar", "stateName": "BIHAR", "displayName": "Bihar", "features": 45063, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/bihar_template.csv"},
  {"slug": "chandigarh", "stateName": "CHANDIGARH", "displayName": "Chandigarh", "features": 13, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/chandigarh_template.csv"},
  {"slug": "chhattisgarh", "stateName": "CHHATTISGARH", "displayName": "Chhattisgarh", "features": 20811, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/chhattisgarh_template.csv"},
  {"slug": "dadra-and-nagar-haveli-and-daman-and-diu", "stateName": "DADRA,NAGAR HAVELI,DAMAN & DIU", "displayName": "Dadra & Nagar Haveli and Daman & Diu", "features": 101, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/dadra-and-nagar-haveli-and-daman-and-diu_template.csv"},
  {"slug": "delhi", "stateName": "DELHI", "displayName": "Delhi", "features": 254, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/delhi_template.csv"},
  {"slug": "goa", "stateName": "GOA", "displayName": "Goa", "features": 412, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/goa_template.csv"},
  {"slug": "gujarat", "stateName": "GUJARAT", "displayName": "Gujarat", "features": 18838, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/gujarat_template.csv"},
  {"slug": "haryana", "stateName": "HARYANA", "displayName": "Haryana", "features": 7010, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/haryana_template.csv"},
  {"slug": "himachal-pradesh", "stateName": "HIMACHAL PRADESH", "displayName": "Himachal Pradesh", "features": 20773, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/himachal-pradesh_template.csv"},
  {"slug": "jammu-and-kashmir", "stateName": "JAMMU & KASHMIR", "displayName": "Jammu & Kashmir", "features": 6593, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/jammu-and-kashmir_template.csv"},
  {"slug": "jharkhand", "stateName": "JHARKHAND", "displayName": "Jharkhand", "features": 32678, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/jharkhand_template.csv"},
  {"slug": "karnataka", "stateName": "KARNATAKA", "displayName": "Karnataka", "features": 29789, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/karnataka_template.csv"},
  {"slug": "kerala", "stateName": "KERALA", "displayName": "Kerala", "features": 1556, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/kerala_template.csv"},
  {"slug": "ladakh", "stateName": "LADAKH", "displayName": "Ladakh", "features": 250, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/ladakh_template.csv"},
  {"slug": "lakshadweep", "stateName": "LAKSHADWEEP", "displayName": "Lakshadweep", "features": 34, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/lakshadweep_template.csv"},
  {"slug": "madhya-pradesh", "stateName": "MADHYA PRADESH", "displayName": "Madhya Pradesh", "features": 55937, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/madhya-pradesh_template.csv"},
  {"slug": "maharashtra", "stateName": "MAHARASHTRA", "displayName": "Maharashtra", "features": 44468, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/maharashtra_template.csv"},
  {"slug": "manipur", "stateName": "MANIPUR", "displayName": "Manipur", "features": 2674, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/manipur_template.csv"},
  {"slug": "meghalaya", "stateName": "MEGHALAYA", "displayName": "Meghalaya", "features": 6897, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/meghalaya_template.csv"},
  {"slug": "mizoram", "stateName": "MIZORAM", "displayName": "Mizoram", "features": 881, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/mizoram_template.csv"},
  {"slug": "nagaland", "stateName": "NAGALAND", "displayName": "Nagaland", "features": 1564, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/nagaland_template.csv"},
  {"slug": "odisha", "stateName": "ODISHA", "displayName": "Odisha", "features": 53320, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/odisha_template.csv"},
  {"slug": "puducherry", "stateName": "PUDUCHERRY", "displayName": "Puducherry", "features": 101, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/puducherry_template.csv"},
  {"slug": "punjab", "stateName": "PUNJAB", "displayName": "Punjab", "features": 12860, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/punjab_template.csv"},
  {"slug": "rajasthan", "stateName": "RAJASTHAN", "displayName": "Rajasthan", "features": 45012, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/rajasthan_template.csv"},
  {"slug": "sikkim", "stateName": "SIKKIM", "displayName": "Sikkim", "features": 484, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/sikkim_template.csv"},
  {"slug": "tamil-nadu", "stateName": "TAMIL NADU", "displayName": "Tamil Nadu", "features": 17119, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/tamil-nadu_template.csv"},
  {"slug": "telangana", "stateName": "TELANGANA", "displayName": "Telangana", "features": 10718, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/telangana_template.csv"},
  {"slug": "tripura", "stateName": "TRIPURA", "displayName": "Tripura", "features": 917, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/tripura_template.csv"},
  {"slug": "uttar-pradesh", "stateName": "UTTAR PRADESH", "displayName": "Uttar Pradesh", "features": 107816, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/uttar-pradesh_template.csv"},
  {"slug": "uttarakhand", "stateName": "UTTARAKHAND", "displayName": "Uttarakhand", "features": 16920, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/uttarakhand_template.csv"},
  {"slug": "west-bengal", "stateName": "WEST BENGAL", "displayName": "West Bengal", "features": 41188, "templateUrl": "https://geo.bharatviz.org/csv/villages-nwdp/west-bengal_template.csv"},
];
