// Generated by scripts/07_build_panchayat_layers.py - do not edit by hand.
// One entry per state with Gram Panchayat boundaries (MoPR AdminGPHierarchy, LGD-coded).
export interface PanchayatStateLayer {
  slug: string;
  stateName: string;
  displayName: string;
  features: number;
}

export const PANCHAYAT_GEOJSON_BASE = 'https://geo.bharatviz.org/geojsons/admin/panchayats';
export const PANCHAYAT_PARQUET_URL = 'https://geo.bharatviz.org/geoparquet/admin/India-lgd-panchayats.parquet';
export const PANCHAYAT_NATIONAL_URL = 'https://geo.bharatviz.org/geojsons/admin/panchayats/india.geojson';

export const PANCHAYAT_STATE_LAYERS: PanchayatStateLayer[] = [
  { slug: 'punjab', stateName: 'PUNJAB', displayName: 'Punjab', features: 10878 },
  { slug: 'uttarakhand', stateName: 'UTTARAKHAND', displayName: 'Uttarakhand', features: 7407 },
  { slug: 'haryana', stateName: 'HARYANA', displayName: 'Haryana', features: 5458 },
  { slug: 'rajasthan', stateName: 'RAJASTHAN', displayName: 'Rajasthan', features: 10950 },
  { slug: 'uttar-pradesh', stateName: 'UTTAR PRADESH', displayName: 'Uttar Pradesh', features: 56137 },
  { slug: 'bihar', stateName: 'BIHAR', displayName: 'Bihar', features: 7877 },
  { slug: 'tripura', stateName: 'TRIPURA', displayName: 'Tripura', features: 601 },
  { slug: 'assam', stateName: 'ASSAM', displayName: 'Assam', features: 2563 },
  { slug: 'west-bengal', stateName: 'WEST BENGAL', displayName: 'West Bengal', features: 3256 },
  { slug: 'jharkhand', stateName: 'JHARKHAND', displayName: 'Jharkhand', features: 4132 },
  { slug: 'odisha', stateName: 'ODISHA', displayName: 'Odisha', features: 6782 },
  { slug: 'chhattisgarh', stateName: 'CHHATTISGARH', displayName: 'Chhattisgarh', features: 11231 },
  { slug: 'madhya-pradesh', stateName: 'MADHYA PRADESH', displayName: 'Madhya Pradesh', features: 21615 },
  { slug: 'gujarat', stateName: 'GUJARAT', displayName: 'Gujarat', features: 13650 },
  { slug: 'maharashtra', stateName: 'MAHARASHTRA', displayName: 'Maharashtra', features: 27352 },
  { slug: 'andhra-pradesh', stateName: 'ANDHRA PRADESH', displayName: 'Andhra Pradesh', features: 10310 },
  { slug: 'karnataka', stateName: 'KARNATAKA', displayName: 'Karnataka', features: 5948 },
  { slug: 'goa', stateName: 'GOA', displayName: 'Goa', features: 178 },
  { slug: 'lakshadweep', stateName: 'LAKSHADWEEP', displayName: 'Lakshadweep', features: 10 },
  { slug: 'kerala', stateName: 'KERALA', displayName: 'Kerala', features: 877 },
  { slug: 'tamil-nadu', stateName: 'TAMIL NADU', displayName: 'Tamil Nadu', features: 11452 },
  { slug: 'puducherry', stateName: 'PUDUCHERRY', displayName: 'Puducherry', features: 71 },
  { slug: 'andaman-nicobar-islands', stateName: 'ANDAMAN & NICOBAR', displayName: 'Andaman & Nicobar Islands', features: 72 },
  { slug: 'telangana', stateName: 'TELANGANA', displayName: 'Telangana', features: 8154 },
  { slug: 'dadra-nagar-haveli-daman-diu', stateName: 'DADRA,NAGAR HAVELI,DAMAN & DIU', displayName: 'Dadra & Nagar Haveli & Daman & Diu', features: 30 },
];
